api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        jsonld: ['application/merge-patch+json'],
        json: ['application/json']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header